backend:
  name: git-gateway
  branch: main

media_folder: "images/productos"
public_folder: "/images/productos"

collections:
  - name: "productos"
    label: "Productos"
    folder: "_productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL amigable (ej: televisor-lg-55-uhd)" }
      - { label: "Marca", name: "brand", widget: "string" }
      - { label: "Imagen Principal", name: "image", widget: "image" }
      - { label: "Galería de Imágenes", name: "gallery", widget: "list", field: { label: "Imagen", name: "image", widget: "image" }, required: false }
      - { label: "Descripción Corta", name: "description", widget: "text" }
      - { label: "Descripción Completa", name: "body", widget: "markdown" }
      - { label: "Precio Regular", name: "price_regular", widget: "number", value_type: "float", required: false }
      - { label: "Precio Online", name: "price_online", widget: "number", value_type: "float" }
      - { label: "Cuota Mensual", name: "monthly_payment", widget: "number", value_type: "float" }
      - { label: "Descuento (%)", name: "discount", widget: "number", value_type: "int", required: false }
      - label: "Categoría"
        name: "category"
        widget: "relation"
        collection: "categorias"
        search_fields: ["title", "slug"]
        value_field: "slug"
        display_fields: ["title"]
      - { label: "Etiquetas", name: "tags", widget: "select", multiple: true, options: ["destacado", "novedad", "oferta", "combo", "reacondicionado", "mas-vendido"], required: false }
      - { label: "Estado", name: "status", widget: "select", options: ["activo", "inactivo"], default: "activo" }
      - { label: "Stock", name: "stock", widget: "number", value_type: "int", default: 1 }
      - { label: "Especificaciones", name: "specs", widget: "list", fields: [
          { label: "Nombre", name: "name", widget: "string" },
          { label: "Valor", name: "value", widget: "string" }
        ], required: false }
      - { label: "Formas de pago", name: "payment_methods", widget: "select", multiple: true, options: ["bcp", "yape", "plin"], default: ["bcp", "yape"], required: false }
      - { label: "Información de envío", name: "shipping", widget: "markdown", required: false }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime" }

  - name: "categorias"
    label: "Categorías"
    folder: "_categorias"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Icono", name: "icon", widget: "image" }
      - { label: "Orden", name: "order", widget: "number", value_type: "int" }

  - name: "configuracion"
    label: "Configuración"
    files:
      - label: "Configuración General"
        name: "general"
        file: "_config/general.yml"
        fields:
          - { label: "Nombre del Sitio", name: "site_name", widget: "string" }
          - { label: "Descripción", name: "site_description", widget: "text" }
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "Teléfono", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "WhatsApp", name: "whatsapp", widget: "string" }

  - name: "catalogo"
    label: "Catálogo"
    files:
      - label: "Catálogo de Productos"
        name: "catalogo"
        file: "data/catalogo.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Slug del producto", name: "slug", widget: "string" }
              - { label: "Visible", name: "visible", widget: "boolean", default: true }
              - { label: "Destacado (Home)", name: "destacado", widget: "boolean", default: false }
              - { label: "Más vendido (Home)", name: "mas_vendido", widget: "boolean", default: false }
              - { label: "Orden", name: "orden", widget: "number", value_type: "int", default: 0 }
              - { label: "Categoría", name: "categoria", widget: "select", required: false, options: ["tecnologia", "electrodomesticos", "muebles", "motos-scooters", "construccion", "gamer", "celulares", "televisores"] }
              - { label: "Marca (opcional)", name: "brand", widget: "string", required: false }
              - { label: "Título (opcional)", name: "title", widget: "string", required: false }
              - { label: "Imagen principal (opcional)", name: "image", widget: "image", required: false }
              - { label: "Precio Online (opcional)", name: "price_online", widget: "number", value_type: "float", required: false }
              - { label: "Precio Regular (opcional)", name: "price_regular", widget: "number", value_type: "float", required: false }
              - { label: "Cuota Mensual (opcional)", name: "monthly_payment", widget: "number", value_type: "float", required: false }
              - { label: "Descuento % (opcional)", name: "discount", widget: "number", value_type: "int", required: false }
              - { label: "Tags (opcional)", name: "tags", widget: "select", multiple: true, required: false, options: ["destacado", "novedad", "oferta", "combo", "reacondicionado", "mas-vendido"] }
